apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-simulator.dataPipelineServiceName" . }}
  labels:
    {{- include "crypto-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-pipeline
spec:
  selector:
    {{- include "crypto-simulator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: data-pipeline
  ports:
    - name: http
      port: {{ .Values.dataPipeline.service.port }}
      targetPort: http
