apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-simulator.postgresServiceName" . }}
  labels:
    {{- include "crypto-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "crypto-simulator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
