apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crypto-simulator-postgres-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: crypto-simulator-postgres-static
